FROM python:3.12-bookworm

WORKDIR /gpt_home_server

COPY . /gpt_home_server

RUN pip install --no-cache-dir .

EXPOSE 8000

ENV GPT_HOME_HA_IGNORE_SSL="true"
ENV GPT_HOME_HA_TOKEN="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiIzNzliOWQzYWVkMTY0ZTRhYTg0ZTgwZGNiMmU3Yjc4MyIsImlhdCI6MTcxMDc5NDA2OSwiZXhwIjoyMDI2MTU0MDY5fQ.jklQBwuYuW2-KsM0rypLsH2Jy8v-tKt8_hXukjGFYYg"
ENV GPT_HOME_HUMAN_NAME="Utkash"
ENV GPT_HOME_AI_NAME="Ida"
ENV GPT_HOME_HA_BASE_URL="https://homeassistant.local:8123"
ENV GPT_HOME_OPENAI_API_KEY="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"

CMD ["python", "backend/server/server.py"]
