repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.9.3
      hooks:
          - id: ruff
            args: [--fix]
            files: \.py$

    - repo: https://github.com/timothycrosley/isort
      rev: 5.13.2
      hooks:
          - id: isort
            args: ["--profile", "black"]
            files: \.py$

    - repo: https://github.com/pre-commit/mirrors-mypy
      rev: v1.14.1
      hooks:
          - id: mypy
            args:
                # if you modify the args, make sure you modify them in backend/pyproject.toml too
                ["--strict", "--ignore-missing-imports", "--check-untyped-defs"]
            additional_dependencies:
                - pydantic
                - pydantic-settings
            files: \.py$

    - repo: https://github.com/igorshubovych/markdownlint-cli
      rev: v0.44.0
      hooks:
          - id: markdownlint
            files: \.(md|markdown)$

    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v5.0.0
      hooks:
          - id: end-of-file-fixer
          - id: trailing-whitespace
          - id: check-added-large-files
            files: \.py$
