version: "1"
services:
    server:
        build: ./backend/Dockerfile.server
        ports:
            - "8000:8000"
    server_proxy:
        build: ./backend/Dockerfile.server_proxy
        ports:
            - "8001:8001"
    frontend:
        build: ./frontend/Dockerfile.frontend
        ports:
            - "3000:3000"
# version: '3.8'
# services:
#   server:
#     build: ./server
#     ports:
#       - "8000:8000"
#     networks:
#       - app-network

#   server_proxy:
#     build: ./server_proxy
#     ports:
#       - "8001:8001"
#     networks:
#       - app-network
#     depends_on:
#       - server

#   frontend:
#     build: ./frontend
#     ports:
#       - "3000:3000"
#     networks:
#       - app-network
#     depends_on:
#       - server
#       - server_proxy

# networks:
#   app-network:
#     driver: bridge
