FROM python:3.12-bookworm

RUN pip install poetry==1.8.2

ENV POETRY_NO_INTERACTION=1 \
    POETRY_VIRTUALENVS_IN_PROJECT=1 \
    POETRY_VIRTUALENVS_CREATE=1 \
    POETRY_CACHE_DIR=/tmp/poetry_cache

WORKDIR /cyris_backend_server

# at first, only install external dependencies (so these layers get cached)
COPY pyproject.toml poetry.lock ./
# this is necessary for `poetry install ...` later
RUN touch README.md
RUN poetry install --without dev --no-root && rm -rf $POETRY_CACHE_DIR

EXPOSE 8000

ARG CYRIS_HA_IGNORE_SSL
ENV CYRIS_HA_IGNORE_SSL=$CYRIS_HA_IGNORE_SSL

ARG CYRIS_HA_TOKEN
ENV CYRIS_HA_TOKEN=$CYRIS_HA_TOKEN

ARG CYRIS_HUMAN_NAME
ENV CYRIS_HUMAN_NAME=$CYRIS_HUMAN_NAME

ARG CYRIS_AI_NAME
ENV CYRIS_AI_NAME=$CYRIS_AI_NAME

ARG CYRIS_HA_BASE_URL
ENV CYRIS_HA_BASE_URL=$CYRIS_HA_BASE_URL

ARG CYRIS_OPENAI_API_KEY
ENV CYRIS_OPENAI_API_KEY=$CYRIS_OPENAI_API_KEY

# Now copy the backend code, which has probably changed since the last `docker build ...`
COPY cyris ./cyris
COPY server ./server

RUN poetry install --without dev

ENTRYPOINT ["poetry", "run", "cyris_backend_server"]
