[project]
name = "cyris_backend"
version = "0.0.1"
description = "I need to think of an appropriate description"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "backend_commons",
    "dspy_wrapper",
    "utils",
    "pydantic[email]>=2.9.2",
    "rich>=13.9.2",
    "fastapi>=0.111.1",
    "uvicorn[standard]>=0.22.0",
    "types-python-jose>=3.3.4.20240106",
    "types-passlib>=1.7.7.20240819",
    "passlib[bcrypt]>=1.7.4",
    "asyncpg>=0.29.0",
    "python-jose[cryptography]>=3.3.0",
]

[tool.uv.sources]
backend_commons = { workspace = true }
dspy_wrapper = { workspace = true }
utils = { workspace = true }

[tool.uv.workspace]
members = ["packages/*"]

[tool.uv]
dev-dependencies = [
    "ipdb>=0.13.13",
    "mypy>=1.11.2",
    "ruff>=0.6.9",
    # "aioconsole>=0.8.1", # occasionally useful for testing async `input()`: `await aioconsole.ainput("send them something ")`
    # "typed-argument-parser>=1.10.1",
]
package = false

[tool.mypy]
strict = true
ignore_missing_imports = true # necessary for `transformers`. See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker
incremental = true
check_untyped_defs = true
