[project]
name = "gpt_home_backend"
version = "0.0.1"
description = "I need to think of an appropriate description"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "homeassistant>=2024.10.2",
    "homeassistant-api>=4.2.2.post1",
    "langchain-openai==0.1.1",
    "langchain==0.1.14",
    "langchainhub==0.1.14",
    "openai>=1.51.2",
    "pydantic[email]>=2.9.2",
    "rich>=13.9.2",
    "torch>=2.2.0,<2.3.0",
    "transformers[torch]>=4.31",
    "fastapi>=0.115.2",
    "uvicorn[standard]>=0.31.1",
    "python-multipart>=0.0.12",
    "types-python-jose>=3.3.4.20240106",
    "types-passlib>=1.7.7.20240819",
    "passlib[bcrypt]>=1.7.4",
    "aiomysql>=0.2.0",
]


# [project.scripts]
# # hello = "example_package_app:hello"
# gpt_home_api_server = "gpt_home_api_server.gpt_home_api_server:main"

[tool.uv]
dev-dependencies = [
    "ipdb>=0.13.13",
    "mypy>=1.11.2",
    "ruff>=0.6.9",
]
package = false


[tool.mypy]
strict = true
ignore_missing_imports = true # necessary for `transformers`. See https://mypy.readthedocs.io/en/stable/running_mypy.html#missing-library-stubs-or-py-typed-marker
incremental = true
