
POST http://localhost:8000/user HTTP/1.1
content-type: application/json

{
    "ai_name": "Fred",
    "human_name": "Utkash"
}

###

GET http://localhost:8000/users HTTP/1.1

###

POST http://localhost:8000/registered_user_client_session HTTP/1.1
content-type: application/json

{
    "client_session_id": "test_client_session_id",
    "user_id": "6d45ef74-9236-49bc-ac2d-c4d4f803b583"
}

###

POST http://localhost:8000/ask_gpt_home HTTP/1.1
content-type: application/json

{
    "senderId": "bad_client_session_id",
    "text": "turn my light on pls"
}

###

POST http://localhost:8000/ask_gpt_home HTTP/1.1
content-type: application/json

{
    "senderId": "test_client_session_id",
    "text": "turn my light off pls"
}

###

DELETE http://localhost:8000/registered_user_client_session HTTP/1.1
content-type: application/json

{
    "client_session_id": "test_client_session_id",
    "user_id": "6d45ef74-9236-49bc-ac2d-c4d4f803b583"
}
