[project]
name = "cyris"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "backend-commons",
    "litellm>=1.58.2",
    "rich>=13.9.2",
    "utils",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv.sources]
utils = { workspace = true }
backend-commons = { workspace = true }
