[project]
name = "gpt_home"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "backend_commons",
    "pydantic>=2.9.2",
    "homeassistant>=2024.10.2",
    "homeassistant-api>=4.2.2.post1",
    "langchain-openai==0.1.1",
    "langchain==0.1.14",
    "langchainhub==0.1.14",
    "openai>=1.51.2",
    "torch>=2.2.0,<2.3.0",
    "transformers[torch]>=4.31",
    "rich>=13.9.2",
]

[tool.uv.sources]
backend_commons = { workspace = true }

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
